language: ruby
services:
  - docker
before_install:
  - docker pull binaryanalysisplatform/bap
  - docker build . -t kennethadammiller/superset_disasm
  - docker build . -f Dockerfile.metrics -t kennethadammiller/superset_disasm_metrics
