language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
sudo: required
cache:
  directories:
    - $HOME/.opam
  before_cache:
    - opam remove superset_disassemblers -y
    - rm -rf $HOME/.opam/log
addons:
  apt:
    sources:
    - avsm
    packages:
    - camlp4
    - camlp4-extra
    - clang
    - curl
    - libcurl4-gnutls-dev
    - libgmp-dev
    - libssl-dev
    - libzip-dev
    - llvm
    - llvm-3.4-dev
    - m4
    - ocaml
    - ocaml-base
    - ocaml-base-nox
    - ocaml-compiler-libs
    - ocaml-native-compilers
    - ocaml-nox
    - time
    - aspcud
    - dejagnu
    - jq
    - opam
env:
  global:
  - OPAMYES=true PACKAGE=superset_disassemblers TESTS=true OPAM_SWITCH=$OCAML_VERSION
  matrix:
  - OCAML_VERSION=4.07
  - OCAML_VERSION=4.09
