language: c
services:
  - docker
install:
  - docker pull binaryanalysisplatform/bap
  - docker build . -t kennethadammiller/superset_disasm
#TODO run tests
#  - docker build . -f Dockerfile.metrics -t kennethadammiller/superset_disasm_metrics
script:
  - echo "Finished!"