language: c
services:
  - docker
before_install:
  - docker pull binaryanalysisplatform/bap
  - docker build . -t kennethadammiller/superset_disasm
#TODO run tests
#  - docker build . -f Dockerfile.metrics -t kennethadammiller/superset_disasm_metrics